### ISSUE TITLE
Generate Crossword Grid

### ISSUE THREAD

**Issue by bsach64** [bsach64/CrosswordPuzzleGenerator#5]

**Comment by ashut0shj** [comment]
Methods to convert 2D array into grids:
using matplotlib : https://www.geeksforgeeks.org/create-2d-pixel-plot-in-python/
using css/js         : https://www.101computing.net/level-generation-using-a-2d-array/

**Comment by bsach64** [comment]
Structuring the code according to this pseudocode
https://www.baeldung.com/cs/generate-crossword-puzzle

**Comment by bsach64** [comment]
A Basic Crossword grid can now be generated using puzzle.py
